export const MESSAGE_TYPES = {
  RELOAD_EXTENSION: 'RELOAD_EXTENSION',
  GET_SETTINGS: 'GET_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  GET_GHOST: 'GET_GHOST',
  SET_GHOST: 'SET_GHOST',
  EXTRACT_MEDIA: 'EXTRACT_MEDIA',
  ACTION_BLOCKED_EVENT: 'ACTION_BLOCKED_EVENT',
  GET_SCHEDULED_POSTS: 'GET_SCHEDULED_POSTS',
  SCHEDULE_POST: 'SCHEDULE_POST',
  DELETE_SCHEDULED_POST: 'DELETE_SCHEDULED_POST',
  GET_AUDIENCE_SNAPSHOT: 'GET_AUDIENCE_SNAPSHOT',
  SCAN_AUDIENCE: 'SCAN_AUDIENCE',
  REMOVE_FOLLOWER: 'REMOVE_FOLLOWER',
  UNFOLLOW_ACCOUNT: 'UNFOLLOW_ACCOUNT',
  BATCH_REMOVE_FOLLOWERS: 'BATCH_REMOVE_FOLLOWERS',
} as const;

export type MessageTypeValue = typeof MESSAGE_TYPES[keyof typeof MESSAGE_TYPES];
