import { useCallback, useEffect, useState } from 'react';
import type { DownloadItem } from '../../shared/types';

export function DownloadsPage() {
  const [url, setUrl] = useState(''); const [items, setItems] = useState<DownloadItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(() => { setLoading(true); chrome.runtime.sendMessage({ type: 'GET_DOWNLOADS' }, (response: DownloadItem[] | { error?: string }) => { setLoading(false); if (Array.isArray(response)) setItems(response); else setError(response?.error ?? 'Could not load downloads.'); }); }, []);
  useEffect(load, [load]);
  const validUrl = /^https:\/\/(?:www\.)?instagram\.com\/(?:p|reel)\/[^/?#&]+/i.test(url.trim());
  const extractCurrent = () => chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => { const tabId = tabs[0]?.id; if (tabId === undefined) { setError('No active tab is available.'); return; } chrome.tabs.sendMessage(tabId, { type: 'EXTRACT_MEDIA' }); });
  return <section aria-labelledby="downloads-title" className="fade-in"><header className="mb-4"><h1 id="downloads-title" className="text-xl font-bold">Downloads</h1><p className="mt-1 text-xs text-gray-400">Open a post, then extract its media.</p></header>
    {error && <div role="alert" className="mb-3 rounded-lg border border-red-900 bg-red-950/50 p-3 text-xs text-red-200">{error}</div>}
    <div className="mb-4 rounded-xl border border-gray-800 bg-gray-900 p-3"><label htmlFor="instagram-url" className="text-[10px] font-bold uppercase tracking-wider text-gray-500">Instagram URL</label><div className="mt-2 flex gap-2"><input id="instagram-url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="instagram.com/p/…" className="min-w-0 flex-1 rounded-lg border border-gray-700 bg-gray-950 px-3 py-2 text-sm outline-none focus:border-pink-500"/><button type="button" disabled={!validUrl} onClick={() => chrome.tabs.create({ url: url.trim() })} className="rounded-lg bg-white px-3 text-xs font-semibold text-gray-950 disabled:opacity-40">Open</button></div><button type="button" onClick={extractCurrent} className="mt-3 w-full rounded-lg border border-gray-700 px-3 py-2 text-xs font-semibold text-gray-200 hover:bg-gray-800">Extract current page</button></div>
    <div className="mb-2 flex items-center justify-between"><h2 className="text-xs font-bold uppercase tracking-wider text-gray-500">Recent</h2><button type="button" onClick={load} className="text-xs text-pink-400">Refresh</button></div>
    {loading ? <p className="py-8 text-center text-sm text-gray-500">Loading downloads…</p> : items.length === 0 ? <div className="rounded-xl border border-dashed border-gray-700 p-7 text-center text-sm text-gray-500">No recent downloads</div> : <ul className="space-y-2">{items.map((item) => <li key={item.id} className="rounded-lg border border-gray-800 bg-gray-900 p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-medium text-gray-200" title={item.filename}>{item.filename}</p><p className="mt-1 text-[11px] text-gray-500">{item.type} · {new Date(item.createdAt).toLocaleString()}</p></div><span className={`rounded px-1.5 py-0.5 text-[10px] font-bold uppercase ${item.status === 'done' ? 'bg-emerald-950 text-emerald-300' : item.status === 'error' ? 'bg-red-950 text-red-300' : 'bg-gray-800 text-gray-300'}`}>{item.status}</span></div>{item.error && <p className="mt-2 text-xs text-red-300">{item.error}</p>}</li>)}</ul>}
  </section>;
}
